# Generated by Django 2.1.7 on 2019-08-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Isbn', models.CharField(max_length=12)),
                ('Calificación', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Autor')),
                ('IdLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Correo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Cedula', models.CharField(max_length=10)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Usuario')),
                ('IdLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Libro')),
            ],
        ),
    ]
