# Generated by Django 2.2.4 on 2019-08-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_libro',
            name='Correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
