# Generated by Django 2.2.3 on 2019-08-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190826_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Calificación',
            new_name='Calificacion',
        ),
    ]
